apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
  namespace: shubha-ns
  labels:
    app: transaction-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
        - name: kyndrl-app-container
          image: muralisocial123/transaction-app:v1.0.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: shubha-ns
spec:
  selector:
    app: transaction
  ports:
    - port: 3003 #It is a service port no., we are using to expose aplication to the internet
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
